kind: Deployment
apiVersion: apps/v1
metadata:
  name: producer-deployment
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: comp4651/producer
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: producer-service
spec:
  type: ClusterIP
  selector:
    app: producer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080